name: 'Build and Test Finances UI'

on:
  push:
    branches: ['main']

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v5

      - name: 'Setup Node Environment'
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'yarn'

      - name: 'Install dependencies'
        run: yarn install

      - name: 'Run Tests'
        run: yarn test
